import React from 'react';
import Head from 'next/head';
import Container from '@/components/shared/Container';
import AboutAndFormSectionDetailsUnit from '@/components/DetailsUnit/AboutAndFormSection';

export default function DetailsUnit() {
  return (
    <React.Fragment>
      <Head>
        <title>Details Unit - Luxelocker</title>
        <meta name='description' content='Generated by Luxelocker' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Container>
          <AboutAndFormSectionDetailsUnit />
        </Container>
      </main>
    </React.Fragment>
  );
}
