import React from 'react';
import Head from 'next/head';
import Container from '@/components/shared/Container';
import ReserveFormAndAboutSection from '@/components/DetailsCampus/AboutAndFormSection';

export default function DetailsCampus() {
  return (
    <React.Fragment>
      <Head>
        <title>Details Campuse - Luxelocker</title>
        <meta name='description' content='Generated by Luxelocker' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Container>
          <ReserveFormAndAboutSection />
        </Container>
      </main>
    </React.Fragment>
  );
}
