import React from 'react';
import Head from 'next/head';
import Appbar from '@/components/shared/AppBar/Appbar';
export default function About() {
    return (
        <React.Fragment>
            <Head>
                <title>About - Luxelocker</title>
                <meta name='description' content='Generated by Luxelocker' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main>
                <Appbar />
            </main>
        </React.Fragment>
    )
}
