//Library Imports
import React, { useEffect } from 'react';
import Head from 'next/head';
import Container from '@/components/shared/Container';
import HeroSectionMeetTheTeam from '@/components/MeetTheTeam/HeroSection';
import MeetTeam from '@/components/MeetTheTeam/MeetTeam';
import ApiController from '@/network/api';
import MeetTheTeamSection from '@/components/MeetTheTeam/MeetTheTeamSection';

const MeetTheTeam = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Meet The Team - Luxelocker</title>
        <meta name='description' content='Generated by Luxelocker' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Container>
          <HeroSectionMeetTheTeam />
          <MeetTheTeamSection />
        </Container>
      </main>
    </React.Fragment>
  );
};
export default MeetTheTeam;
