import React from 'react';
import Head from 'next/head';
import Container from '@/components/shared/Container';
import HeroSection from '@/components/Home/HeroSection';
import AboutLuxeLocker from '@/components/Home/About';
import StorageUnits from '@/components/Home/StorageUnits';
import ReservationForm from '@/components/Home/ReservationForm';
import UsersLoveLuxelocker from '@/components/Home/UsersLoveLuxelocker';
import GetStarted from '@/components/Home/GetStarted';
import BlogSection from '@/components/Home/BlogSection';
import LocationDetails from '@/components/Home/LocationDetails';

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Home - Luxelocker</title>
        <meta name='description' content='Generated by Luxelocker' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Container>
          <HeroSection />
          <AboutLuxeLocker />
          <StorageUnits />
          <LocationDetails />
          <ReservationForm />
          <UsersLoveLuxelocker />
          <GetStarted />
          <BlogSection />
        </Container>
      </main>
    </React.Fragment>
  );
}
