import React from 'react';
import Head from 'next/head';
import Container from '@/components/shared/Container';
import GetStartedBlogs from '@/components/Blog/GetStartedBlogs';
import FAQsMainSection from '@/components/FAQs/FAQsMainSection';

export default function FAQs() {
  return (
    <React.Fragment>
      <Head>
        <title>FAQs - Luxelocker</title>
        <meta name='description' content='Generated by Luxelocker' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Container>
          <FAQsMainSection />
          <GetStartedBlogs />
        </Container>
      </main>
    </React.Fragment>
  );
}
