//Library Imports
import React from 'react';
import Head from 'next/head';
import { useSelector } from 'react-redux';
import Container from '@/components/shared/Container';
import HeroSectionLocationsSearch from '@/components/Locations/LocationSearchPage/HeroSection';
import SearchResults from '@/components/Locations/LocationSearchPage/SearchedResults';
import AboutUnitDetailsLocationPage from '@/components/Locations/LocationSearchPage/AboutSection';
import MapUnitDetails from '@/components/Locations/LocationSearchPage/MapUnitDetails';
import GetStarted from '@/components/Home/GetStarted';
import BlogSection from '@/components/Home/BlogSection';
import { RootState } from '@/redux/store';
const PreviewLocations = () => {
  const searchedDetailsHero = useSelector(
    (state: RootState) =>
      state?.globalSearcedHeroDetailsReducer?.globalSearchedHeroDetails
  );
  return (
    <React.Fragment>
      <Head>
        <title>Location Search - Luxelocker</title>
        <meta name='description' content='Generated by Luxelocker' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <HeroSectionLocationsSearch />
        <Container>
          <SearchResults />
          {searchedDetailsHero?.pathName !== 'Home' && (
            <React.Fragment>
              <AboutUnitDetailsLocationPage />
              <MapUnitDetails />
              <GetStarted />
              <BlogSection />
            </React.Fragment>
          )}
        </Container>
      </main>
    </React.Fragment>
  );
};
export default PreviewLocations;
