import React from 'react';
import Head from 'next/head';
import Container from '@/components/shared/Container';
import HeroSectionAndBlogsSection from '@/components/Blog/HeroSectionAndBlogs';
import GetStartedBlogs from '@/components/Blog/GetStartedBlogs';
export default function Blogs() {
  return (
    <React.Fragment>
      <Head>
        <title>Blogs - Luxelocker</title>
        <meta name='description' content='Generated by Luxelocker' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Container>
          <HeroSectionAndBlogsSection />
          <GetStartedBlogs />
        </Container>
      </main>
    </React.Fragment>
  );
}
