import React from 'react';
import Head from 'next/head';
import Container from '@/components/shared/Container';
import SinglePostSection from '@/components/Blog/SingleBlog/SinglePostSection';
import GetStarted from '@/components/Home/GetStarted';

export default function SingleBlog() {
  return (
    <React.Fragment>
      <Head>
        <title>Blog - Luxelocker</title>
        <meta name='description' content='Generated by Luxelocker' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Container>
          <SinglePostSection />
          <GetStarted />
        </Container>
      </main>
    </React.Fragment>
  );
}
